Library
LeoJulia/external-courses pull request #11
Opened 2018-12-06 19:19 UTC by LeoJulia

Создала массив с книгами BOOKS. При загрузке страница, происходит событие, которое отрисовывает div.library со всеми книгами. 
Создала функцию rating, которая просматривает rating у книг и плавно отрисовывает его под(за ними) звездочками.
Попыталась создать функцию onHoverStar(event) использую mouseover, чтобы при наведении сбрасывалась заполненность звездочек и заполнялась в зависимость от действий пользователя. 
Не получилось вернуть изначальную заполненность из массива.

2018-12-08 14:57 UTC, LeoJulia commented
избавилась от функции onHoverStar(event) и проставляю рейтинг с помощью css

2018-12-08 16:23 UTC, LeoJulia commented
создала функцию handleChangeSearch, которая осуществляет поиск по названию и автору книги

2018-12-08 21:05 UTC, eugrdn commented on src/library/script.js
> +function rating(rating, elem){
эту функцию ты назвала `rating`, по такому же принципу, что и ниже `book`? только делают они разные вещи, одна рассчитывает заполнение рейтингом, другая  -- создает елемент, тогда было бы логичнее назвать функцией `rating` то, где ты создаешь `radio`.
а так вообще функция должна именоваться по тому, что она делает, и обычно с глаголом, т.е `create...`, `get...`, `calculate...`, и тп.

2018-12-08 21:05 UTC, eugrdn commented on src/library/script.js
> +    xhr.onreadystatechange = function() {
почему `onreadystatechange`, а не `onload`?

2018-12-08 21:05 UTC, eugrdn commented on src/library/script.js
> +function library(obj){
`obj === BOOKS`? используй что-то одно), и ниже вместо `for` используй `forEach`, раз это массив

2018-12-08 21:05 UTC, eugrdn commented on src/library/script.js
> +    BOOKS.forEach(function(i){
в данном случае удобнее использовать `filter`

2018-12-08 21:05 UTC, eugrdn commented on src/library/script.js
> +    for(var i = 0; i < result.length; i++){
используй forEach

2018-12-08 21:05 UTC, eugrdn commented on src/library/script.js
> +    var response;
не используется

2018-12-08 22:30 UTC, LeoJulia commented
Добавила модальное окно и возможность добавлять книги в библиотеку.
Исправила все замечания

2018-12-08 22:36 UTC, LeoJulia commented on src/library/script.js
> +    xhr.onreadystatechange = function() {
решила, что это более надежный вариант в плане кроссбраузерности, но не современности)
в последнем коммите уже исправила на onload

2018-12-09 08:07 UTC, eugrdn reviewed
по поводу стабильности `onreadystatechange`, да, и не обязательно сразу вностить правки, главное, чтобы ты понимала, чем они отличаются :)

2018-12-09 08:07 UTC, eugrdn commented on src/library/script.js
> +    BOOKS.filter(function(i){
`filter` возвразает новый массив `result.push(i);` писать излишне

P.S. `i` так обычно сокращают индекс (2 аргумент, а не первый)

2018-12-09 08:07 UTC, eugrdn commented on src/library/script.js
> +        bookItem.setAttribute("data-id", i);
лучше не задавать `id` элементов по их индексу, а сделать функцию, которая всегда возвращает уникальное значение и использовать ее при создании нового объекта

сделал чтобы книжки из api приходили с `id`

2018-12-09 16:33 UTC, LeoJulia commented
создала событие при нажатие на фильтры

2018-12-09 20:08 UTC, LeoJulia commented
добавила оповещения на добавление книги

2018-12-15 22:39 UTC, LeoJulia commented
Закончила разделять файл script.js по паттерну mvc

2018-12-16 13:24 UTC, eugrdn requested changes
> Закончила разделять файл script.js по паттерну mvc

забыла реализовать модель

2018-12-16 13:24 UTC, eugrdn commented on src/library/script.js
> +    this.showAll = function(){
хмм, а почему через `this`? и `filter.addEventListener('click', filteringBook);` у тебя на каждый `click` будет выполняться вся функция, т.е будут создаваться все методы, использоваться будет лишь один :(

2018-12-16 13:24 UTC, eugrdn commented on src/library/script.js
> +        var result = BOOKS.map(function(item){
зачем здесь `map`?

2018-12-16 13:24 UTC, eugrdn commented on src/library/script.js
> +    BOOKS.forEach(function(item){
то, что делает эта функция у тебя объявляется так же в 5 других местах

2018-12-16 13:24 UTC, eugrdn commented on src/library/script.js
> +        if(i === arr.length - 2){
можно объединить условия, раз результат один и тот же

2018-12-16 13:24 UTC, eugrdn commented on src/library/controllers/LibraryController.js
> +    let utils = Utils;
зачем создавать новую переменную?
ps у аргумента может быть любое имя

2018-12-16 13:24 UTC, eugrdn commented on src/library/view/LibraryView.js
> +    function init(){
33-45 строки нужно вынести в отдельную функцию, можно положить в утилиты

2018-12-16 13:24 UTC, eugrdn commented on src/library/controllers/LibraryController.js
> +        showLibrary: showLibrary,
ps в es6 можно использовать краткий синтаксис https://ponyfoo.com/articles/es6#object-literals (1)

2018-12-16 13:24 UTC, eugrdn commented on src/library/controllers/LibraryController.js
> +            if(i === arr.length - 2){
объедини условие с предыдущем, раз результат одинаковый

2018-12-16 13:24 UTC, eugrdn commented on src/library/controllers/LibraryController.js
> +    function createBook(obj){
это должно быть во view (работа с DOM)

2018-12-16 13:24 UTC, eugrdn commented on src/library/controllers/LibraryController.js
> +    function showLibrary(obj){
тоже view

2018-12-16 13:24 UTC, eugrdn commented on src/library/index.html
> +    <script src="./index.js"></script>
а где модель? :)

2018-12-16 13:24 UTC, eugrdn commented on src/library/controllers/LibraryController.js
> +    let BOOKS;
это + history + все сортировки/фильтрации данных модели, должно быть в модели

2018-12-16 16:35 UTC, LeoJulia commented on src/library/script.js
> +        var result = BOOKS.map(function(item){
так как я не хочу, чтобы основной массив BOOKS фильтровался, поэтому сначала делаю копию BOOKS, а после на месте фильтрую методом sort, и получившийся массив отображаю

2018-12-16 16:45 UTC, LeoJulia commented on src/library/script.js
> +    this.showAll = function(){
воспользовалась делегированием событий, т. е. на все меню с фильтрами. а там в зависимости от того на каком элементе был клик, будет выполняться одна из фильтраций
Сейчас увидела, что можно улучшить код, вынеся переменную result за пределы методов в основную функцию и в условии после вызова фильтра уже отображать отфильтрованный массив result

2018-12-17 09:37 UTC, eugrdn commented on src/library/script.js
> +        var result = BOOKS.map(function(item){
в таком случае используют `.slice`, `.map` хоть и дает результат такой же, но создавался для других целей

2018-12-17 09:51 UTC, LeoJulia commented
исправила все замечания

2018-12-18 16:48 UTC, eugrdn commented on src/library/utils/Utils.js
> +    function setTamiAgo(date){
Time :)

2018-12-18 16:48 UTC, eugrdn commented on src/library/models/LibraryModel.js
> +            if(item.title.toLowerCase().indexOf(value) !== -1 ||
раз это filter, то достаточно возвращать `boolean` значение, ты же возвращаешь либо `item`, либо `undefined` в данном случае можо написать просто
```
return (
            item.title.toLowerCase().indexOf(value) !== -1 ||
            item.author.firstName.toLowerCase().indexOf(value) !== -1 ||
            item.author.lastName.toLowerCase().indexOf(value) !== -1)
);
```

2018-12-18 16:48 UTC, eugrdn commented on src/library/models/LibraryModel.js
> +        this.showAll = function(){
почему бы просто не сделать switch по типам фильтров showAll,showRecent...?

2018-12-18 16:48 UTC, eugrdn commented on src/library/controllers/LibraryController.js
> +    function openModal() {
почему это в контроллере? вроде решали перенести во view?

2018-12-18 16:48 UTC, eugrdn commented on src/library/controllers/LibraryController.js
> +        var titleInput = document.querySelectorAll(".modal__form--input")[0];
controller не должен знать про `document`

2018-12-18 17:28 UTC, eugrdn approved these changes

2018-12-18 17:28 UTC, merged